### ISSUE TITLE
A bug of tables

### ISSUE THREAD

**Issue by KtuluWU** [bueltge/Markdown-for-MantisBT#8]
Hello
How are you?

I found a bug of tables.
Version of Mantis: 1.3.0-rc1-dev

The text-align of tables does not work because in the style.css of mantis, we have:

![1](https://cloud.githubusercontent.com/assets/17195210/15668604/841a46ea-271c-11e6-9095-a0fdc050bac0.png)

So i tried to edit the code of  "markdown-extra.php" on the line 2376-2379, and create a file of css.
![2](https://cloud.githubusercontent.com/assets/17195210/15668731/0335a686-271d-11e6-8131-90ce4202d18f.png)
![3](https://cloud.githubusercontent.com/assets/17195210/15668736/091e30e0-271d-11e6-9d66-1da74d850ee1.png)

It works now, so I recommend you to edit the code :-) 

Thank you very much!

**Comment by bueltge** [comment]
I think it is not a good idea to provide stylesheet information from a plugin, is more a topic for the theme. 
But maybe we should not add the attribute `align`, we should add a css class, so that it easy to add custom rules via CSS. Like `class="right"` instead of `align="right"`.
What do you think?

**Comment by bueltge** [comment]
The Colorized Theme have now also the support active - https://github.com/bueltge/MantisBT-Colorized

**Comment by KtuluWU** [comment]
Ok Thank you for your answer, its better than mine. :-)

**Comment by bueltge** [comment]
Welcome. :+1:
